# Numpy. Домашнее Задание. Ultra-Pro

In [ ]:
import numpy as np

### Задача 1
*(1 балл)*

Создайте единичную матрицу размером 5*5.

**Должна получиться матрица вида**

**1** 0 0 0 0

0 **1** 0 0 0

0 0 **1** 0 0

0 0 0 **1** 0

0 0 0 0 **1**

**Действовать можно двумя путями:**

1. Используя соответствующий метод Numpy. (О нем не говорилось в занятии. Стоит обратиться к документации Numpy).
2. Если первый вариант сложный, можно создать массив из нулей, используя метод, о котором говорилось в занятии. В цикле заменить все элементы по диагонали на единицы.






**Решение:**

In [ ]:
print(arr := np.identity(5, dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


###Задача 2
*(2 балла)*

Создайте массив из случайных значений из стандартного нормального распределения размера 6 на 6.

Разверните массив таким образом, чтобы его размер стал 36 на 1.
Найдите среднее значение элементов массива.

**Разрешается использовать только методы Numpy. (Циклы и условия запрещены)**.

**Решение:**

In [ ]:
new_arr = np.random.randn(6, 6)
new_arr2 = np.reshape(new_arr, (36, 1))

aver1 = np.mean(new_arr)
aver2 = np.mean(new_arr2)
print(aver1, aver2)

-0.035167521531228214 -0.035167521531228214


###Задача 3
*(2 балла)*

Создайте массив из 20 любых случайных значений, используя метод Numpy.
Найдите значения производных для созданного массива

**Решение:**

In [ ]:
print(test_array := np.random.randint(1, 100, 20))
print(np.diff(test_array))

[20 20 23 89 30 26 97 91 46  5 35 37 92 64 31 58 85 75 38 71]
[  0   3  66 -59  -4  71  -6 -45 -41  30   2  55 -28 -33  27  27 -10 -37
  33]


###Задача 4
*(2 балла)*

Дано выражение

Y = A * X * C

Создайте три случайных массива A, C, X. Размерности должны позволять выполнить матричное умножение согласно формуле. На выходе должен получиться массив Y с размерностью (5, 18). (Остальные размерности возьмите на свое усмотрение).

**Решение:**

In [ ]:
A = np.random.randint(0, 100, (5, 8))
X = np.random.randint(0, 100, (8, 10))
C = np.random.randint(0, 100, (10, 18))
print(np.dot( np.dot(A, X), C))

[[11837922  8043513 11813590 14478160  8287591 12217562 10799250  9375168
   9338482 13825618 14852193 12323553 12412676 17665782 14811579  8512629
   8061997 10260419]
 [ 8832465  6478950  8965375 11446735  6695532  9502961  8064674  7302922
   7399434 10316852 11530356  9578634 10087765 13494400 11439428  6373187
   6505648  8181988]
 [ 7645165  5222764  7755318  9610173  5667395  8366823  7363005  6139025
   6663486  9171635  9484424  7748366  8292146 11966328  9424549  5472197
   5369666  6702771]
 [12073159  8288031 12100802 14668924  8308870 12526394 10506917  9644066
   9439521 13672049 15099341 12648986 12843525 17676207 15017127  8625461
   8231165 10637391]
 [ 7924063  6059089  8203775 10489961  6010877  8647713  7252307  6972858
   6624294  9015045 10755236  9004147  9327570 11824487 10356105  5807280
   5890661  7470257]]


###Задача 5
*(3 балла)*

Загрузите какой-либо файл с данными (таблица Excel с Вашего компьютера, сохраненная в формате csv, или таблица из Интернета). Выведите следующее:

1. Всю информацию из файла в ячейку.
2. Размерность данных.
3. Среднее арифметическое от всех числовых значений (если есть).
4. Число столбов.
5. Число строк.
6. Типы данных всех значений.

**Решение:**

In [ ]:
arr = np.loadtxt('iris.csv', delimiter=',', skiprows=1)

In [ ]:
print(arr, '\n\n')
print(arr.shape, '\n\n')
print(arr.mean, '\n\n')
print(arr.shape[1], '\n\n')
print(arr.shape[0], '\n\n')
arr.dtype

[[0.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [1.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [3.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [4.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [5.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [6.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [7.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [8.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [9.00e+00 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.00e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.10e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.30e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.40e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.50e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.60e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.70e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.80e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [1.90e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.00e+01 5.40e+00 3.40e+00 1.70e+00 2.

dtype('float64')