# Numpy. Домашнее Задание. Pro

*2 балла за каждую задачу*

In [ ]:
import numpy as np

### Задача 1
*(2 балла)*

* Подгрузите массив с файла **iris.csv** и назовите этот массив my_array.

* Создайте двумерный массив из случайных чисел той же размерности, что и my_array (раздел "Семплирование из распределений", потребуется использовать размерность массива my_array).

* Назовите его my_generated_array.

**Решение:**

In [ ]:
fname = 'iris.csv'
my_array = np.loadtxt(fname, delimiter=',', skiprows = 1)
my_generated_array = np.random.randint(1, 100, my_array.shape)

### Задача 2
*(2 балла)*

* Выполните поэлементное умножение my_array на my_generated_array (раздел "Векторные операции").

* Склейте массивы my_array, my_generated_array в один (могут помочь методы np.concatenate, np.vstack, np.hstack).

* Возьмите склеенный массив и разделите его на равные части (больше двух). Можно сделать вручную через циклы либо воспользоваться методом vsplit.

**Решение:**

In [ ]:
print(my_array * my_generated_array)
print(new_array := np.concatenate([my_array, my_generated_array]))
print(np.vsplit(new_array, 3))

[[0.0000e+00 4.9980e+02 7.0000e+00 9.8000e+00 4.0000e+00]
 [6.0000e+00 2.9400e+01 5.1000e+01 1.4000e+00 1.8000e+00]
 [1.2600e+02 1.2690e+02 1.8880e+02 6.8900e+01 9.0000e+00]
 [2.4000e+01 1.3340e+02 2.1700e+01 1.3050e+02 1.7600e+01]
 [3.6800e+02 1.3500e+02 1.7640e+02 1.3440e+02 4.0000e+00]
 [4.0000e+02 4.8060e+02 1.1700e+01 2.3800e+01 2.0800e+01]
 [3.4800e+02 3.1280e+02 1.3600e+02 6.1600e+01 1.8000e+00]
 [4.9000e+01 4.0000e+01 2.0400e+02 9.1500e+01 8.0000e+00]
 [6.8800e+02 8.8000e+00 6.6700e+01 9.8000e+01 1.0000e+01]
 [7.5600e+02 3.4790e+02 2.5110e+02 1.0500e+01 6.7000e+00]
 [7.2000e+02 1.1880e+02 2.2200e+02 1.2450e+02 9.2000e+00]
 [1.0890e+03 3.4080e+02 2.3120e+02 5.1200e+01 1.1800e+01]
 [6.2400e+02 1.7760e+02 1.2000e+02 2.8000e+01 1.5000e+00]
 [5.8500e+02 1.5910e+02 3.0000e+00 8.2500e+01 6.4000e+00]
 [3.2200e+02 4.4080e+02 1.1200e+02 2.0400e+01 1.6800e+01]
 [7.8000e+02 8.5500e+01 1.1880e+02 1.4700e+02 2.7600e+01]
 [1.7600e+02 3.8340e+02 2.7300e+01 1.1960e+02 3.0400e+01]
 [1.1220e+03 3

### Задача 3
*(2 балла)*

* Найдите все элементы массива my_array, которые больше трех и меньше 5 одновременно. Используйте методологию подвыборки массива с условием (раздел "Индексация").

**Решение:**

In [ ]:
print(my_array[(my_array > 3) & (my_array < 5)])

[3.5 4.9 4.7 3.2 4.6 3.1 4.  3.6 3.9 4.6 3.4 3.4 4.4 4.9 3.1 3.7 4.8 3.4
 4.8 4.3 4.  4.4 3.9 3.5 3.8 3.8 3.4 3.7 4.6 3.6 3.3 4.8 3.4 3.4 3.5 3.4
 4.7 3.2 4.8 3.1 3.4 4.1 4.2 4.9 3.1 3.2 3.5 4.9 3.6 4.4 3.4 3.5 4.5 4.4
 3.2 3.5 3.8 4.8 3.8 4.6 3.2 3.7 3.3 3.2 4.7 3.2 4.5 3.1 4.9 4.  4.6 4.5
 3.3 4.7 4.9 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 3.1 4.4 4.5 4.1 4.5 3.9 3.2
 4.8 4.  4.9 4.7 4.3 4.4 4.8 4.5 3.5 3.8 3.7 3.9 4.5 3.4 4.5 3.1 4.7 4.4
 4.1 4.  4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 4.1 3.3 4.9 4.5 3.6 3.2 3.2 3.8
 3.2 4.9 4.9 3.3 3.2 4.8 4.9 3.8 3.4 3.1 4.8 3.1 3.1 3.1 3.2 3.3 3.4]


### Задача 4
*(2 балла)*

Создайте трехмерный массив размера 2 на 3 на 4, состоящий из случайных ВЕЩЕСТВЕННЫХ чисел от 15 до 37. Используйте встроенные методы библиотеки  np.random.

**Решение:**

In [ ]:
print(arr := np.random.uniform(15, 37, (2, 3, 4)))

[[[36.46617238 30.08204917 28.57524928 24.37787699]
  [23.04394471 20.9030572  18.25702552 36.12652922]
  [16.80818193 19.70437688 32.77268184 15.82270402]]

 [[27.01073367 29.37236968 36.28847023 31.01134885]
  [27.25161351 21.60118008 35.46102904 22.12346245]
  [26.7294627  19.73339847 15.34933208 31.35725434]]]


### Задача 5
*(2 балла)*

Используя массив из предыдущей задачи, преобразуйте его в новый массив со следующими значениями:

    * "small", если значения меньше 20
    * "medium", если значения в промежутке [20, 30]
    * "large", если значения больше 30

**Решение:**

In [ ]:
new_arr = np.full((2, 3, 4), 'medium', dtype='U64')
new_arr[arr < 20] = 'small'
new_arr[arr > 30] = 'large'
print(new_arr)

[[['large' 'large' 'medium' 'medium']
  ['medium' 'medium' 'small' 'large']
  ['small' 'small' 'large' 'small']]

 [['medium' 'medium' 'large' 'large']
  ['medium' 'medium' 'large' 'medium']
  ['medium' 'small' 'small' 'large']]]
